apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gtrainer
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 30s
  timeout: 5m
  path: ./deploy/gtrainer
  serviceAccountName: gtrainer-reconciler
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
